// Code generated by protoc-gen-go.
// source: access_server.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	access_server.proto
	base.proto
	error.proto
	gateway.proto
	msg_server.proto

It has these top-level messages:
	ReqLogin
	ResLogin
	ReqLogout
	ResLogout
	Base
	Error
	ReqMsgServer
	ResSelectMsgServerForClient
	ReqSendP2PMsg
	ResSendP2PMsg
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// login
type ReqLogin struct {
	Cmd    uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	UID    int64  `protobuf:"varint,3,opt,name=UID" json:"UID,omitempty"`
	Token  string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *ReqLogin) Reset()                    { *m = ReqLogin{} }
func (m *ReqLogin) String() string            { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()               {}
func (*ReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResLogin struct {
	Cmd     uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr  string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	ErrCode uint32 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,4,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ResLogin) Reset()                    { *m = ResLogin{} }
func (m *ResLogin) String() string            { return proto.CompactTextString(m) }
func (*ResLogin) ProtoMessage()               {}
func (*ResLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// logout
type ReqLogout struct {
	Cmd    uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	UID    int64  `protobuf:"varint,3,opt,name=UID" json:"UID,omitempty"`
}

func (m *ReqLogout) Reset()                    { *m = ReqLogout{} }
func (m *ReqLogout) String() string            { return proto.CompactTextString(m) }
func (*ReqLogout) ProtoMessage()               {}
func (*ReqLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ResLogout struct {
	Cmd     uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr  string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	ErrCode uint32 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,4,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ResLogout) Reset()                    { *m = ResLogout{} }
func (m *ResLogout) String() string            { return proto.CompactTextString(m) }
func (*ResLogout) ProtoMessage()               {}
func (*ResLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*ReqLogin)(nil), "protocol.ReqLogin")
	proto.RegisterType((*ResLogin)(nil), "protocol.ResLogin")
	proto.RegisterType((*ReqLogout)(nil), "protocol.ReqLogout")
	proto.RegisterType((*ResLogout)(nil), "protocol.ResLogout")
}

func init() { proto.RegisterFile("access_server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4c, 0x4e, 0x4e,
	0x2d, 0x2e, 0x8e, 0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x31, 0x5c, 0x1c, 0x41, 0xa9, 0x85, 0x3e, 0xf9, 0xe9,
	0x99, 0x79, 0x42, 0x02, 0x5c, 0xcc, 0xc9, 0xb9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41,
	0x20, 0xa6, 0x90, 0x18, 0x17, 0x5b, 0x72, 0x6e, 0x4a, 0x70, 0x49, 0x91, 0x04, 0x93, 0x02, 0xa3,
	0x06, 0x67, 0x10, 0x94, 0x07, 0x52, 0x19, 0xea, 0xe9, 0x22, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1c,
	0x04, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0xe4, 0x67, 0xa7, 0xe6, 0x49, 0xb0, 0x80, 0x15, 0x42,
	0x38, 0x4a, 0x69, 0x20, 0xd3, 0x8b, 0x49, 0x35, 0x5d, 0x82, 0x8b, 0x3d, 0xb5, 0xa8, 0xc8, 0x39,
	0x3f, 0x25, 0x15, 0x6c, 0x03, 0x6f, 0x10, 0x8c, 0x0b, 0xd2, 0x91, 0x5a, 0x54, 0x04, 0xd2, 0x01,
	0xb1, 0x06, 0xca, 0x53, 0x72, 0xe7, 0xe2, 0x84, 0xf8, 0x22, 0xbf, 0xb4, 0x84, 0x12, 0x6f, 0x28,
	0xa5, 0x83, 0x0c, 0x2a, 0x26, 0xd9, 0x20, 0x92, 0x5d, 0x9c, 0xc4, 0x06, 0x8e, 0x01, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x44, 0x13, 0x26, 0x9f, 0x01, 0x00, 0x00,
}
