// Code generated by protoc-gen-go.
// source: gateway.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ReqMsgServer struct {
	Label            *string `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReqMsgServer) Reset()                    { *m = ReqMsgServer{} }
func (m *ReqMsgServer) String() string            { return proto.CompactTextString(m) }
func (*ReqMsgServer) ProtoMessage()               {}
func (*ReqMsgServer) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ReqMsgServer) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqMsgServer)(nil), "protocol.ReqMsgServer")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0x2c, 0x49,
	0x2d, 0x4f, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39,
	0x4a, 0xb2, 0x5c, 0x3c, 0x41, 0xa9, 0x85, 0xbe, 0xc5, 0xe9, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45,
	0x42, 0xbc, 0x5c, 0xac, 0x39, 0x89, 0x49, 0xa9, 0x39, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0x70, 0xc9, 0xdc, 0x38, 0x00, 0x00, 0x00,
}
