// Code generated by protoc-gen-go.
// source: msg_server.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// login
type ReqLogin struct {
	Cmd    uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	UID    int64  `protobuf:"varint,3,opt,name=UID,json=uID" json:"UID,omitempty"`
	Token  string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *ReqLogin) Reset()                    { *m = ReqLogin{} }
func (m *ReqLogin) String() string            { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()               {}
func (*ReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type ResLogin struct {
	Cmd     uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr  string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	ErrCode uint32 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,4,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ResLogin) Reset()                    { *m = ResLogin{} }
func (m *ResLogin) String() string            { return proto.CompactTextString(m) }
func (*ResLogin) ProtoMessage()               {}
func (*ResLogin) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

// logout
type ReqLogout struct {
	Cmd    uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	UID    int64  `protobuf:"varint,3,opt,name=UID,json=uID" json:"UID,omitempty"`
}

func (m *ReqLogout) Reset()                    { *m = ReqLogout{} }
func (m *ReqLogout) String() string            { return proto.CompactTextString(m) }
func (*ReqLogout) ProtoMessage()               {}
func (*ReqLogout) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type ResLogout struct {
	Cmd     uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr  string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	ErrCode uint32 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,4,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ResLogout) Reset()                    { *m = ResLogout{} }
func (m *ResLogout) String() string            { return proto.CompactTextString(m) }
func (*ResLogout) ProtoMessage()               {}
func (*ResLogout) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

// p2p msg
type ReqSendP2PMsg struct {
	Cmd       uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr    string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	TargetUID int64  `protobuf:"varint,3,opt,name=targetUID" json:"targetUID,omitempty"`
	Msg       string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *ReqSendP2PMsg) Reset()                    { *m = ReqSendP2PMsg{} }
func (m *ReqSendP2PMsg) String() string            { return proto.CompactTextString(m) }
func (*ReqSendP2PMsg) ProtoMessage()               {}
func (*ReqSendP2PMsg) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

type ResSendP2PMsg struct {
	Cmd     uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdStr  string `protobuf:"bytes,2,opt,name=cmdStr" json:"cmdStr,omitempty"`
	ErrCode uint32 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,4,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ResSendP2PMsg) Reset()                    { *m = ResSendP2PMsg{} }
func (m *ResSendP2PMsg) String() string            { return proto.CompactTextString(m) }
func (*ResSendP2PMsg) ProtoMessage()               {}
func (*ResSendP2PMsg) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func init() {
	proto.RegisterType((*ReqLogin)(nil), "protocol.ReqLogin")
	proto.RegisterType((*ResLogin)(nil), "protocol.ResLogin")
	proto.RegisterType((*ReqLogout)(nil), "protocol.ReqLogout")
	proto.RegisterType((*ResLogout)(nil), "protocol.ResLogout")
	proto.RegisterType((*ReqSendP2PMsg)(nil), "protocol.ReqSendP2PMsg")
	proto.RegisterType((*ResSendP2PMsg)(nil), "protocol.ResSendP2PMsg")
}

func init() { proto.RegisterFile("msg_server.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0xa3, 0xb5, 0x3b, 0xb0, 0x50, 0x82, 0x48, 0x0e, 0x1e, 0x96, 0x9c, 0xf6, 0xe4,
	0x41, 0x7f, 0x82, 0x05, 0x29, 0x28, 0x94, 0x14, 0x6f, 0x82, 0xe8, 0x66, 0x0c, 0xa5, 0x66, 0x63,
	0x27, 0xa9, 0xbf, 0x5f, 0x26, 0xbb, 0xd2, 0x73, 0xec, 0x29, 0xf3, 0xc2, 0xcc, 0xfb, 0xe6, 0xc1,
	0xc0, 0xc2, 0x47, 0xf7, 0x16, 0x91, 0x7e, 0x90, 0x6e, 0xbf, 0x29, 0xa4, 0x20, 0xe7, 0xf9, 0xe9,
	0xc3, 0x97, 0x7e, 0x85, 0xb9, 0xc1, 0xfd, 0x53, 0x70, 0xdb, 0x41, 0x2e, 0x40, 0xf4, 0xde, 0xaa,
	0xaa, 0xad, 0xba, 0xc6, 0x70, 0x29, 0xaf, 0x61, 0xd6, 0x7b, 0xbb, 0x49, 0xa4, 0xce, 0xda, 0xaa,
	0xab, 0xcd, 0xa4, 0xb8, 0xf3, 0x65, 0xb5, 0x54, 0xa2, 0xad, 0x3a, 0x61, 0xc4, 0x61, 0xb5, 0x94,
	0x57, 0x70, 0x91, 0xc2, 0x0e, 0x07, 0x75, 0x9e, 0x1b, 0x47, 0xa1, 0x3f, 0xd9, 0x3d, 0x96, 0xba,
	0x2b, 0xb8, 0x44, 0xa2, 0x87, 0x60, 0x31, 0x13, 0x1a, 0xf3, 0x27, 0x79, 0x02, 0x89, 0x78, 0x62,
	0xc4, 0x4c, 0x4a, 0x3f, 0x42, 0x3d, 0xa6, 0x08, 0x87, 0x74, 0x4a, 0x0c, 0xed, 0xd8, 0x28, 0x16,
	0x1b, 0x95, 0x6f, 0xbc, 0x85, 0xc6, 0xe0, 0x7e, 0x83, 0x83, 0x5d, 0xdf, 0xad, 0x9f, 0xa3, 0x2b,
	0x80, 0xdd, 0x40, 0x9d, 0xde, 0xc9, 0x61, 0x3a, 0xee, 0x7e, 0xfc, 0x60, 0x1f, 0x1f, 0xdd, 0x44,
	0xe3, 0x52, 0xef, 0x18, 0x15, 0xff, 0x85, 0x2a, 0xce, 0xf5, 0x31, 0xcb, 0x97, 0x75, 0xff, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x94, 0x42, 0xba, 0x34, 0x74, 0x02, 0x00, 0x00,
}
