// Code generated by protoc-gen-go.
// source: access_server.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	access_server.proto
	manager.proto
	msg_server.proto
	router.proto

It has these top-level messages:
	ASSendP2PMsgReq
	ASSendP2PMsgRes
	LoginReq
	LoginRes
	SendP2PMsgReq
	SendP2PMsgRes
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ASSendP2PMsgReq struct {
	UID       int64  `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	Msg       string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *ASSendP2PMsgReq) Reset()                    { *m = ASSendP2PMsgReq{} }
func (m *ASSendP2PMsgReq) String() string            { return proto.CompactTextString(m) }
func (*ASSendP2PMsgReq) ProtoMessage()               {}
func (*ASSendP2PMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ASSendP2PMsgRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ASSendP2PMsgRes) Reset()                    { *m = ASSendP2PMsgRes{} }
func (m *ASSendP2PMsgRes) String() string            { return proto.CompactTextString(m) }
func (*ASSendP2PMsgRes) ProtoMessage()               {}
func (*ASSendP2PMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*ASSendP2PMsgReq)(nil), "rpc.ASSendP2PMsgReq")
	proto.RegisterType((*ASSendP2PMsgRes)(nil), "rpc.ASSendP2PMsgRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for AccessServerRPC service

type AccessServerRPCClient interface {
	SendP2PMsg(ctx context.Context, in *ASSendP2PMsgReq, opts ...grpc.CallOption) (*ASSendP2PMsgRes, error)
}

type accessServerRPCClient struct {
	cc *grpc.ClientConn
}

func NewAccessServerRPCClient(cc *grpc.ClientConn) AccessServerRPCClient {
	return &accessServerRPCClient{cc}
}

func (c *accessServerRPCClient) SendP2PMsg(ctx context.Context, in *ASSendP2PMsgReq, opts ...grpc.CallOption) (*ASSendP2PMsgRes, error) {
	out := new(ASSendP2PMsgRes)
	err := grpc.Invoke(ctx, "/rpc.AccessServerRPC/SendP2PMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccessServerRPC service

type AccessServerRPCServer interface {
	SendP2PMsg(context.Context, *ASSendP2PMsgReq) (*ASSendP2PMsgRes, error)
}

func RegisterAccessServerRPCServer(s *grpc.Server, srv AccessServerRPCServer) {
	s.RegisterService(&_AccessServerRPC_serviceDesc, srv)
}

func _AccessServerRPC_SendP2PMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASSendP2PMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServerRPCServer).SendP2PMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AccessServerRPC/SendP2PMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServerRPCServer).SendP2PMsg(ctx, req.(*ASSendP2PMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessServerRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.AccessServerRPC",
	HandlerType: (*AccessServerRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendP2PMsg",
			Handler:    _AccessServerRPC_SendP2PMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("access_server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8f, 0x31, 0x8b, 0x83, 0x40,
	0x10, 0x85, 0xcf, 0x5b, 0xf0, 0x70, 0xe0, 0xf0, 0xd8, 0x0b, 0x41, 0x42, 0x0a, 0xb1, 0xb2, 0xb2,
	0x30, 0x5d, 0x3a, 0x31, 0x4d, 0x0a, 0x41, 0x76, 0x49, 0x1d, 0xcc, 0x3a, 0x58, 0x25, 0x9a, 0x99,
	0x25, 0xbf, 0x3f, 0xec, 0x92, 0x20, 0x48, 0xba, 0xf7, 0x3e, 0x86, 0x8f, 0x37, 0xf0, 0xdf, 0x19,
	0x83, 0xcc, 0x67, 0x46, 0x7a, 0x20, 0x15, 0x13, 0x8d, 0x76, 0x94, 0x82, 0x26, 0x93, 0x69, 0x88,
	0x2b, 0xad, 0xf1, 0xd6, 0xb7, 0x65, 0xdb, 0xf0, 0xa0, 0xf0, 0x2e, 0xff, 0x40, 0x9c, 0x8e, 0x87,
	0x24, 0x48, 0x83, 0x5c, 0x28, 0x17, 0xe5, 0x16, 0x22, 0xdb, 0xd1, 0x80, 0xd6, 0xf1, 0x6f, 0xcf,
	0x67, 0xe0, 0xee, 0xaf, 0x3c, 0x24, 0x22, 0x0d, 0xf2, 0x48, 0xb9, 0x98, 0xd5, 0x4b, 0x29, 0xcb,
	0x04, 0x7e, 0x90, 0xa8, 0x1e, 0x7b, 0xf4, 0xe2, 0x5f, 0xf5, 0xae, 0x72, 0x0d, 0x21, 0x12, 0x69,
	0x4b, 0xde, 0x1c, 0xa9, 0x57, 0x2b, 0x1b, 0x88, 0x2b, 0xbf, 0x5a, 0xfb, 0xd1, 0xaa, 0xad, 0xe5,
	0x1e, 0x60, 0xb6, 0xca, 0x55, 0x41, 0x93, 0x29, 0x16, 0xeb, 0x37, 0x9f, 0x28, 0x67, 0x5f, 0x97,
	0xd0, 0x3f, 0xbd, 0x7b, 0x06, 0x00, 0x00, 0xff, 0xff, 0x71, 0xd2, 0x53, 0x81, 0x0b, 0x01, 0x00,
	0x00,
}
