// Code generated by protoc-gen-go.
// source: access.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	access.proto
	logic.proto
	register.proto

It has these top-level messages:
	ASSendP2PMsgReq
	ASSendP2PMsgRes
	LoginReq
	LoginRes
	PingReq
	PingRes
	SendP2PMsgReq
	SendP2PMsgRes
	AcceptP2PMsgAckReq
	AcceptP2PMsgAckRes
	RGLoginReq
	RGLoginRes
	RGAccessReq
	RGAccessRes
	RGAuthReq
	RGAuthRes
	RGPingReq
	RGPingRes
	RGOnlineReq
	RGOnlineRes
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ASSendP2PMsgReq struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	Msg       string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *ASSendP2PMsgReq) Reset()                    { *m = ASSendP2PMsgReq{} }
func (m *ASSendP2PMsgReq) String() string            { return proto.CompactTextString(m) }
func (*ASSendP2PMsgReq) ProtoMessage()               {}
func (*ASSendP2PMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ASSendP2PMsgReq) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *ASSendP2PMsgReq) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *ASSendP2PMsgReq) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *ASSendP2PMsgReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ASSendP2PMsgRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ASSendP2PMsgRes) Reset()                    { *m = ASSendP2PMsgRes{} }
func (m *ASSendP2PMsgRes) String() string            { return proto.CompactTextString(m) }
func (*ASSendP2PMsgRes) ProtoMessage()               {}
func (*ASSendP2PMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ASSendP2PMsgRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ASSendP2PMsgRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

func init() {
	proto.RegisterType((*ASSendP2PMsgReq)(nil), "rpc.ASSendP2PMsgReq")
	proto.RegisterType((*ASSendP2PMsgRes)(nil), "rpc.ASSendP2PMsgRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AccessServerRPC service

type AccessServerRPCClient interface {
	SendP2PMsg(ctx context.Context, in *ASSendP2PMsgReq, opts ...grpc.CallOption) (*ASSendP2PMsgRes, error)
}

type accessServerRPCClient struct {
	cc *grpc.ClientConn
}

func NewAccessServerRPCClient(cc *grpc.ClientConn) AccessServerRPCClient {
	return &accessServerRPCClient{cc}
}

func (c *accessServerRPCClient) SendP2PMsg(ctx context.Context, in *ASSendP2PMsgReq, opts ...grpc.CallOption) (*ASSendP2PMsgRes, error) {
	out := new(ASSendP2PMsgRes)
	err := grpc.Invoke(ctx, "/rpc.AccessServerRPC/SendP2PMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccessServerRPC service

type AccessServerRPCServer interface {
	SendP2PMsg(context.Context, *ASSendP2PMsgReq) (*ASSendP2PMsgRes, error)
}

func RegisterAccessServerRPCServer(s *grpc.Server, srv AccessServerRPCServer) {
	s.RegisterService(&_AccessServerRPC_serviceDesc, srv)
}

func _AccessServerRPC_SendP2PMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASSendP2PMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServerRPCServer).SendP2PMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AccessServerRPC/SendP2PMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServerRPCServer).SendP2PMsg(ctx, req.(*ASSendP2PMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessServerRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.AccessServerRPC",
	HandlerType: (*AccessServerRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendP2PMsg",
			Handler:    _AccessServerRPC_SendP2PMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access.proto",
}

func init() { proto.RegisterFile("access.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0xab, 0x95, 0x0c, 0x4a, 0x65, 0x28, 0xb2, 0x88, 0x87, 0x92, 0x53, 0x4f, 0x39,
	0xd4, 0x9b, 0xb7, 0x92, 0x5e, 0x7a, 0x28, 0x84, 0x5d, 0xfc, 0x01, 0x71, 0x33, 0xec, 0x29, 0x6e,
	0x9c, 0xd9, 0xf8, 0xfb, 0x25, 0x1b, 0x35, 0x10, 0x7a, 0xdb, 0xf7, 0x3d, 0xd8, 0x8f, 0x37, 0x70,
	0xdf, 0x38, 0x47, 0x22, 0x65, 0xcf, 0x21, 0x06, 0x54, 0xdc, 0xbb, 0x62, 0x80, 0xf5, 0xc1, 0x5a,
	0xfa, 0x6c, 0xeb, 0x7d, 0x7d, 0x16, 0x6f, 0xe8, 0x0b, 0x5f, 0x20, 0x97, 0x30, 0xb0, 0xa3, 0xf7,
	0xd3, 0x51, 0x67, 0xdb, 0x6c, 0xa7, 0xcc, 0x0c, 0xc6, 0x36, 0x36, 0xec, 0x29, 0x8e, 0xed, 0xf5,
	0xd4, 0xfe, 0x03, 0xdc, 0xc0, 0x6d, 0x27, 0xfe, 0x74, 0xd4, 0x6a, 0x9b, 0xed, 0x72, 0x33, 0x05,
	0x7c, 0x04, 0xd5, 0x89, 0xd7, 0x37, 0x89, 0x8d, 0xcf, 0xa2, 0x5a, 0x6a, 0x05, 0x35, 0xdc, 0x11,
	0x73, 0x15, 0x5a, 0x4a, 0xd2, 0x07, 0xf3, 0x17, 0xf1, 0x09, 0x56, 0xc4, 0x6c, 0x23, 0x27, 0x5f,
	0x6e, 0x7e, 0xd3, 0xfe, 0x0c, 0xeb, 0x43, 0x1a, 0x64, 0x89, 0xbf, 0x89, 0x4d, 0x5d, 0xe1, 0x1b,
	0xc0, 0xfc, 0x2b, 0x6e, 0x4a, 0xee, 0x5d, 0xb9, 0xd8, 0xf7, 0x7c, 0x89, 0x4a, 0x71, 0xf5, 0xb1,
	0x4a, 0x67, 0x79, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xbd, 0xe8, 0x8e, 0x26, 0x01, 0x00,
	0x00,
}
