// Code generated by protoc-gen-go.
// source: access.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	access.proto
	idgen.proto
	logic.proto
	manager.proto
	notify.proto
	register.proto

It has these top-level messages:
	ASSendP2PMsgReq
	ASSendP2PMsgRes
	ASSendP2PMsgFromJobReq
	ASSendP2PMsgFromJobRes
	ASOffsetP2PMsg
	ASSendNotifyReq
	ASSendNotifyRes
	ASSendGroupMsgReq
	ASSendGroupMsgRes
	Snowflake
	LoginReq
	LoginRes
	PingReq
	PingRes
	SendP2PMsgReq
	SendP2PMsgRes
	SyncMsgReq
	OffsetP2PMsg
	SyncMsgRes
	AcceptP2PMsgAckReq
	AcceptP2PMsgAckRes
	SendGroupMsgReq
	SendGroupMsgRes
	MGExceptionMsgReq
	MGExceptionMsgRes
	MGOfflineMsgReq
	OfflineMsg
	MGOfflineMsgRes
	MGSyncMsgReq
	MGSyncMsgRes
	NFNotifyMsgReq
	NFNotifyMsgRes
	RGRegisterReq
	RGRegisterRes
	RGLoginReq
	RGLoginRes
	RGAccessReq
	RGAccessRes
	RGAuthReq
	RGAuthRes
	RGPingReq
	RGPingRes
	RGOnlineReq
	RGOnlineRes
	RGCreateGroupReq
	RGCreateGroupRes
	RGJoinGroupReq
	RGJoinGroupRes
	RGQuitGroupReq
	RGQuitGroupRes
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ASSendP2PMsgReq struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	Msg       string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *ASSendP2PMsgReq) Reset()                    { *m = ASSendP2PMsgReq{} }
func (m *ASSendP2PMsgReq) String() string            { return proto.CompactTextString(m) }
func (*ASSendP2PMsgReq) ProtoMessage()               {}
func (*ASSendP2PMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ASSendP2PMsgReq) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *ASSendP2PMsgReq) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *ASSendP2PMsgReq) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *ASSendP2PMsgReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ASSendP2PMsgRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ASSendP2PMsgRes) Reset()                    { *m = ASSendP2PMsgRes{} }
func (m *ASSendP2PMsgRes) String() string            { return proto.CompactTextString(m) }
func (*ASSendP2PMsgRes) ProtoMessage()               {}
func (*ASSendP2PMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ASSendP2PMsgRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ASSendP2PMsgRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

type ASSendP2PMsgFromJobReq struct {
	SourceUID        int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID        int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID            string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	Msg              string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
	AccessServerAddr string `protobuf:"bytes,5,opt,name=accessServerAddr" json:"accessServerAddr,omitempty"`
}

func (m *ASSendP2PMsgFromJobReq) Reset()                    { *m = ASSendP2PMsgFromJobReq{} }
func (m *ASSendP2PMsgFromJobReq) String() string            { return proto.CompactTextString(m) }
func (*ASSendP2PMsgFromJobReq) ProtoMessage()               {}
func (*ASSendP2PMsgFromJobReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ASSendP2PMsgFromJobReq) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *ASSendP2PMsgFromJobReq) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *ASSendP2PMsgFromJobReq) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *ASSendP2PMsgFromJobReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ASSendP2PMsgFromJobReq) GetAccessServerAddr() string {
	if m != nil {
		return m.AccessServerAddr
	}
	return ""
}

type ASSendP2PMsgFromJobRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ASSendP2PMsgFromJobRes) Reset()                    { *m = ASSendP2PMsgFromJobRes{} }
func (m *ASSendP2PMsgFromJobRes) String() string            { return proto.CompactTextString(m) }
func (*ASSendP2PMsgFromJobRes) ProtoMessage()               {}
func (*ASSendP2PMsgFromJobRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ASSendP2PMsgFromJobRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ASSendP2PMsgFromJobRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

type ASOffsetP2PMsg struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	Msg       string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *ASOffsetP2PMsg) Reset()                    { *m = ASOffsetP2PMsg{} }
func (m *ASOffsetP2PMsg) String() string            { return proto.CompactTextString(m) }
func (*ASOffsetP2PMsg) ProtoMessage()               {}
func (*ASOffsetP2PMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ASOffsetP2PMsg) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *ASOffsetP2PMsg) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *ASOffsetP2PMsg) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *ASOffsetP2PMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ASSendNotifyReq struct {
	UID              int64  `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
	CurrentID        int64  `protobuf:"varint,2,opt,name=currentID" json:"currentID,omitempty"`
	TotalID          int64  `protobuf:"varint,3,opt,name=totalID" json:"totalID,omitempty"`
	AccessServerAddr string `protobuf:"bytes,4,opt,name=accessServerAddr" json:"accessServerAddr,omitempty"`
}

func (m *ASSendNotifyReq) Reset()                    { *m = ASSendNotifyReq{} }
func (m *ASSendNotifyReq) String() string            { return proto.CompactTextString(m) }
func (*ASSendNotifyReq) ProtoMessage()               {}
func (*ASSendNotifyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ASSendNotifyReq) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *ASSendNotifyReq) GetCurrentID() int64 {
	if m != nil {
		return m.CurrentID
	}
	return 0
}

func (m *ASSendNotifyReq) GetTotalID() int64 {
	if m != nil {
		return m.TotalID
	}
	return 0
}

func (m *ASSendNotifyReq) GetAccessServerAddr() string {
	if m != nil {
		return m.AccessServerAddr
	}
	return ""
}

type ASSendNotifyRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ASSendNotifyRes) Reset()                    { *m = ASSendNotifyRes{} }
func (m *ASSendNotifyRes) String() string            { return proto.CompactTextString(m) }
func (*ASSendNotifyRes) ProtoMessage()               {}
func (*ASSendNotifyRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ASSendNotifyRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ASSendNotifyRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

type ASSendGroupMsgReq struct {
	GroupID int64  `protobuf:"varint,1,opt,name=groupID" json:"groupID,omitempty"`
	MsgID   string `protobuf:"bytes,2,opt,name=msgID" json:"msgID,omitempty"`
	Msg     string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *ASSendGroupMsgReq) Reset()                    { *m = ASSendGroupMsgReq{} }
func (m *ASSendGroupMsgReq) String() string            { return proto.CompactTextString(m) }
func (*ASSendGroupMsgReq) ProtoMessage()               {}
func (*ASSendGroupMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ASSendGroupMsgReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *ASSendGroupMsgReq) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *ASSendGroupMsgReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ASSendGroupMsgRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *ASSendGroupMsgRes) Reset()                    { *m = ASSendGroupMsgRes{} }
func (m *ASSendGroupMsgRes) String() string            { return proto.CompactTextString(m) }
func (*ASSendGroupMsgRes) ProtoMessage()               {}
func (*ASSendGroupMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ASSendGroupMsgRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ASSendGroupMsgRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

func init() {
	proto.RegisterType((*ASSendP2PMsgReq)(nil), "rpc.ASSendP2PMsgReq")
	proto.RegisterType((*ASSendP2PMsgRes)(nil), "rpc.ASSendP2PMsgRes")
	proto.RegisterType((*ASSendP2PMsgFromJobReq)(nil), "rpc.ASSendP2PMsgFromJobReq")
	proto.RegisterType((*ASSendP2PMsgFromJobRes)(nil), "rpc.ASSendP2PMsgFromJobRes")
	proto.RegisterType((*ASOffsetP2PMsg)(nil), "rpc.ASOffsetP2PMsg")
	proto.RegisterType((*ASSendNotifyReq)(nil), "rpc.ASSendNotifyReq")
	proto.RegisterType((*ASSendNotifyRes)(nil), "rpc.ASSendNotifyRes")
	proto.RegisterType((*ASSendGroupMsgReq)(nil), "rpc.ASSendGroupMsgReq")
	proto.RegisterType((*ASSendGroupMsgRes)(nil), "rpc.ASSendGroupMsgRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AccessServerRPC service

type AccessServerRPCClient interface {
	SendP2PMsgFromJob(ctx context.Context, in *ASSendP2PMsgFromJobReq, opts ...grpc.CallOption) (*ASSendP2PMsgFromJobRes, error)
	SendNotify(ctx context.Context, in *ASSendNotifyReq, opts ...grpc.CallOption) (*ASSendNotifyRes, error)
}

type accessServerRPCClient struct {
	cc *grpc.ClientConn
}

func NewAccessServerRPCClient(cc *grpc.ClientConn) AccessServerRPCClient {
	return &accessServerRPCClient{cc}
}

func (c *accessServerRPCClient) SendP2PMsgFromJob(ctx context.Context, in *ASSendP2PMsgFromJobReq, opts ...grpc.CallOption) (*ASSendP2PMsgFromJobRes, error) {
	out := new(ASSendP2PMsgFromJobRes)
	err := grpc.Invoke(ctx, "/rpc.AccessServerRPC/SendP2PMsgFromJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServerRPCClient) SendNotify(ctx context.Context, in *ASSendNotifyReq, opts ...grpc.CallOption) (*ASSendNotifyRes, error) {
	out := new(ASSendNotifyRes)
	err := grpc.Invoke(ctx, "/rpc.AccessServerRPC/SendNotify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccessServerRPC service

type AccessServerRPCServer interface {
	SendP2PMsgFromJob(context.Context, *ASSendP2PMsgFromJobReq) (*ASSendP2PMsgFromJobRes, error)
	SendNotify(context.Context, *ASSendNotifyReq) (*ASSendNotifyRes, error)
}

func RegisterAccessServerRPCServer(s *grpc.Server, srv AccessServerRPCServer) {
	s.RegisterService(&_AccessServerRPC_serviceDesc, srv)
}

func _AccessServerRPC_SendP2PMsgFromJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASSendP2PMsgFromJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServerRPCServer).SendP2PMsgFromJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AccessServerRPC/SendP2PMsgFromJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServerRPCServer).SendP2PMsgFromJob(ctx, req.(*ASSendP2PMsgFromJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessServerRPC_SendNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASSendNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServerRPCServer).SendNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AccessServerRPC/SendNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServerRPCServer).SendNotify(ctx, req.(*ASSendNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessServerRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.AccessServerRPC",
	HandlerType: (*AccessServerRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendP2PMsgFromJob",
			Handler:    _AccessServerRPC_SendP2PMsgFromJob_Handler,
		},
		{
			MethodName: "SendNotify",
			Handler:    _AccessServerRPC_SendNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access.proto",
}

func init() { proto.RegisterFile("access.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0xcb, 0x6a, 0xc2, 0x40,
	0x14, 0x86, 0x8d, 0xe3, 0x05, 0x0f, 0xbd, 0xe8, 0x20, 0x12, 0x6c, 0x17, 0x92, 0x95, 0x74, 0xe1,
	0xc2, 0xee, 0xba, 0x93, 0xd8, 0x16, 0x85, 0x56, 0x99, 0xe0, 0x03, 0x68, 0x32, 0x86, 0x42, 0x75,
	0xd2, 0x33, 0x93, 0x42, 0x9f, 0xa0, 0x6f, 0xd1, 0x75, 0x1f, 0xb3, 0x4c, 0xae, 0xa2, 0xb1, 0x0b,
	0x17, 0xee, 0xf2, 0xff, 0x27, 0x9c, 0x7f, 0xce, 0x77, 0x26, 0x81, 0x8b, 0xa5, 0xeb, 0x72, 0x29,
	0x07, 0x01, 0x0a, 0x25, 0x28, 0xc1, 0xc0, 0xb5, 0x42, 0xb8, 0x1e, 0x39, 0x0e, 0xdf, 0x7a, 0xf3,
	0xe1, 0xfc, 0x45, 0xfa, 0x8c, 0x7f, 0xd0, 0x5b, 0x68, 0x48, 0x11, 0xa2, 0xcb, 0x17, 0x93, 0xb1,
	0x69, 0xf4, 0x8c, 0x3e, 0x61, 0xb9, 0xa1, 0xab, 0x6a, 0x89, 0x3e, 0x57, 0xba, 0x5a, 0x8e, 0xab,
	0x99, 0x41, 0xdb, 0x50, 0xdd, 0x48, 0x7f, 0x32, 0x36, 0x49, 0xcf, 0xe8, 0x37, 0x58, 0x2c, 0x68,
	0x13, 0xc8, 0x46, 0xfa, 0x66, 0x25, 0xf2, 0xf4, 0xa3, 0x65, 0xef, 0xc7, 0x4a, 0x6a, 0x42, 0x9d,
	0x23, 0xda, 0xc2, 0xe3, 0x51, 0xe8, 0x25, 0x4b, 0x25, 0xed, 0x40, 0x8d, 0x23, 0x3a, 0x0a, 0xa3,
	0xbc, 0x06, 0x4b, 0x94, 0xf5, 0x6b, 0x40, 0x67, 0xb7, 0xcb, 0x13, 0x8a, 0xcd, 0x54, 0xac, 0xce,
	0x34, 0x03, 0xbd, 0x83, 0x66, 0xcc, 0xd3, 0xe1, 0xf8, 0xc9, 0x71, 0xe4, 0x79, 0x68, 0x56, 0xa3,
	0xf2, 0x81, 0x6f, 0x4d, 0x8f, 0x9c, 0xf4, 0x94, 0xb1, 0x15, 0x5c, 0x8d, 0x9c, 0xd9, 0x7a, 0x2d,
	0xb9, 0x8a, 0xbb, 0x9d, 0x65, 0x63, 0xdf, 0x46, 0xba, 0xb2, 0x57, 0xa1, 0xde, 0xd6, 0x5f, 0x9a,
	0x72, 0x13, 0x48, 0x9e, 0x48, 0x92, 0x2c, 0x37, 0x44, 0xe4, 0x5b, 0x95, 0x67, 0x65, 0x86, 0x9e,
	0x55, 0x09, 0xb5, 0x7c, 0x4f, 0xd2, 0x08, 0x4b, 0x65, 0x21, 0xcb, 0xca, 0x11, 0x96, 0xf6, 0xfe,
	0x41, 0x4e, 0x81, 0xb8, 0x80, 0x56, 0xdc, 0xe4, 0x19, 0x45, 0x18, 0x24, 0x37, 0xdf, 0x84, 0xba,
	0xaf, 0x65, 0x36, 0x53, 0x2a, 0x73, 0x4a, 0xe5, 0x02, 0x4a, 0x24, 0xa7, 0xf4, 0x78, 0xd8, 0xf6,
	0x84, 0xd3, 0x0d, 0x7f, 0x34, 0xec, 0x9d, 0xb9, 0xd9, 0xdc, 0xa6, 0x33, 0x68, 0x1d, 0x5c, 0x20,
	0x7a, 0x33, 0xc0, 0xc0, 0x1d, 0x14, 0x7f, 0x04, 0xdd, 0x7f, 0x8a, 0xd2, 0x2a, 0xd1, 0x07, 0x80,
	0x9c, 0x22, 0x6d, 0xef, 0xbc, 0x9c, 0x6d, 0xb8, 0x5b, 0xe4, 0x4a, 0xab, 0xb4, 0xaa, 0x45, 0xbf,
	0x90, 0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x62, 0x65, 0x7a, 0x52, 0x04, 0x00, 0x00,
}
