// Code generated by protoc-gen-go.
// source: access_server.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	access_server.proto
	manager.proto
	msg_server.proto
	router.proto

It has these top-level messages:
	LoginReq
	LoginRes
	SendP2PMsgReq
	SendP2PMsgRes
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for AccessServerRPC service

type AccessServerRPCClient interface {
}

type accessServerRPCClient struct {
	cc *grpc.ClientConn
}

func NewAccessServerRPCClient(cc *grpc.ClientConn) AccessServerRPCClient {
	return &accessServerRPCClient{cc}
}

// Server API for AccessServerRPC service

type AccessServerRPCServer interface {
}

func RegisterAccessServerRPCServer(s *grpc.Server, srv AccessServerRPCServer) {
	s.RegisterService(&_AccessServerRPC_serviceDesc, srv)
}

var _AccessServerRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.AccessServerRPC",
	HandlerType: (*AccessServerRPCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    fileDescriptor0,
}

func init() { proto.RegisterFile("access_server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 68 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4c, 0x4e, 0x4e,
	0x2d, 0x2e, 0x8e, 0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2e, 0x2a, 0x48, 0x36, 0x12, 0xe4, 0xe2, 0x77, 0x04, 0xcb, 0x05, 0x83, 0xa5, 0x82, 0x02,
	0x9c, 0x93, 0xd8, 0xc0, 0xd2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0xa9, 0xba, 0x44,
	0x35, 0x00, 0x00, 0x00,
}
