// Code generated by protoc-gen-go.
// source: logic.proto
// DO NOT EDIT!

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LoginReq struct {
	UID        int64  `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
	Token      string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	AccessAddr string `protobuf:"bytes,3,opt,name=accessAddr" json:"accessAddr,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *LoginReq) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *LoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginReq) GetAccessAddr() string {
	if m != nil {
		return m.AccessAddr
	}
	return ""
}

type LoginRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *LoginRes) Reset()                    { *m = LoginRes{} }
func (m *LoginRes) String() string            { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()               {}
func (*LoginRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *LoginRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *LoginRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

type PingReq struct {
	UID int64 `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
}

func (m *PingReq) Reset()                    { *m = PingReq{} }
func (m *PingReq) String() string            { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()               {}
func (*PingReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *PingReq) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type PingRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *PingRes) Reset()                    { *m = PingRes{} }
func (m *PingRes) String() string            { return proto.CompactTextString(m) }
func (*PingRes) ProtoMessage()               {}
func (*PingRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *PingRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *PingRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

type SendP2PMsgReq struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	MsgType   string `protobuf:"bytes,4,opt,name=msgType" json:"msgType,omitempty"`
	Msg       string `protobuf:"bytes,5,opt,name=msg" json:"msg,omitempty"`
}

func (m *SendP2PMsgReq) Reset()                    { *m = SendP2PMsgReq{} }
func (m *SendP2PMsgReq) String() string            { return proto.CompactTextString(m) }
func (*SendP2PMsgReq) ProtoMessage()               {}
func (*SendP2PMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *SendP2PMsgReq) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *SendP2PMsgReq) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *SendP2PMsgReq) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *SendP2PMsgReq) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *SendP2PMsgReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SendP2PMsgRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *SendP2PMsgRes) Reset()                    { *m = SendP2PMsgRes{} }
func (m *SendP2PMsgRes) String() string            { return proto.CompactTextString(m) }
func (*SendP2PMsgRes) ProtoMessage()               {}
func (*SendP2PMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *SendP2PMsgRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *SendP2PMsgRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

// sync msg
type SyncMsgReq struct {
	UID       int64 `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
	CurrentID int64 `protobuf:"varint,2,opt,name=currentID" json:"currentID,omitempty"`
	TotalID   int64 `protobuf:"varint,3,opt,name=totalID" json:"totalID,omitempty"`
}

func (m *SyncMsgReq) Reset()                    { *m = SyncMsgReq{} }
func (m *SyncMsgReq) String() string            { return proto.CompactTextString(m) }
func (*SyncMsgReq) ProtoMessage()               {}
func (*SyncMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *SyncMsgReq) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *SyncMsgReq) GetCurrentID() int64 {
	if m != nil {
		return m.CurrentID
	}
	return 0
}

func (m *SyncMsgReq) GetTotalID() int64 {
	if m != nil {
		return m.TotalID
	}
	return 0
}

type OffsetP2PMsg struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	Msg       string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *OffsetP2PMsg) Reset()                    { *m = OffsetP2PMsg{} }
func (m *OffsetP2PMsg) String() string            { return proto.CompactTextString(m) }
func (*OffsetP2PMsg) ProtoMessage()               {}
func (*OffsetP2PMsg) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *OffsetP2PMsg) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *OffsetP2PMsg) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *OffsetP2PMsg) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *OffsetP2PMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SyncMsgRes struct {
	ErrCode uint32          `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string          `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
	P2PMsgs []*OffsetP2PMsg `protobuf:"bytes,3,rep,name=p2pMsgs" json:"p2pMsgs,omitempty"`
}

func (m *SyncMsgRes) Reset()                    { *m = SyncMsgRes{} }
func (m *SyncMsgRes) String() string            { return proto.CompactTextString(m) }
func (*SyncMsgRes) ProtoMessage()               {}
func (*SyncMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *SyncMsgRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *SyncMsgRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

func (m *SyncMsgRes) GetP2PMsgs() []*OffsetP2PMsg {
	if m != nil {
		return m.P2PMsgs
	}
	return nil
}

// p2p msg accept ack
type AcceptP2PMsgAckReq struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
}

func (m *AcceptP2PMsgAckReq) Reset()                    { *m = AcceptP2PMsgAckReq{} }
func (m *AcceptP2PMsgAckReq) String() string            { return proto.CompactTextString(m) }
func (*AcceptP2PMsgAckReq) ProtoMessage()               {}
func (*AcceptP2PMsgAckReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *AcceptP2PMsgAckReq) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *AcceptP2PMsgAckReq) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *AcceptP2PMsgAckReq) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

type AcceptP2PMsgAckRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *AcceptP2PMsgAckRes) Reset()                    { *m = AcceptP2PMsgAckRes{} }
func (m *AcceptP2PMsgAckRes) String() string            { return proto.CompactTextString(m) }
func (*AcceptP2PMsgAckRes) ProtoMessage()               {}
func (*AcceptP2PMsgAckRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *AcceptP2PMsgAckRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *AcceptP2PMsgAckRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

// group msg
type SendGroupMsgReq struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	GroupID   int64  `protobuf:"varint,2,opt,name=groupID" json:"groupID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	Msg       string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *SendGroupMsgReq) Reset()                    { *m = SendGroupMsgReq{} }
func (m *SendGroupMsgReq) String() string            { return proto.CompactTextString(m) }
func (*SendGroupMsgReq) ProtoMessage()               {}
func (*SendGroupMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *SendGroupMsgReq) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *SendGroupMsgReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *SendGroupMsgReq) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *SendGroupMsgReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SendGroupMsgRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *SendGroupMsgRes) Reset()                    { *m = SendGroupMsgRes{} }
func (m *SendGroupMsgRes) String() string            { return proto.CompactTextString(m) }
func (*SendGroupMsgRes) ProtoMessage()               {}
func (*SendGroupMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *SendGroupMsgRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *SendGroupMsgRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "rpc.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "rpc.LoginRes")
	proto.RegisterType((*PingReq)(nil), "rpc.PingReq")
	proto.RegisterType((*PingRes)(nil), "rpc.PingRes")
	proto.RegisterType((*SendP2PMsgReq)(nil), "rpc.SendP2PMsgReq")
	proto.RegisterType((*SendP2PMsgRes)(nil), "rpc.SendP2PMsgRes")
	proto.RegisterType((*SyncMsgReq)(nil), "rpc.SyncMsgReq")
	proto.RegisterType((*OffsetP2PMsg)(nil), "rpc.offsetP2PMsg")
	proto.RegisterType((*SyncMsgRes)(nil), "rpc.SyncMsgRes")
	proto.RegisterType((*AcceptP2PMsgAckReq)(nil), "rpc.AcceptP2PMsgAckReq")
	proto.RegisterType((*AcceptP2PMsgAckRes)(nil), "rpc.AcceptP2PMsgAckRes")
	proto.RegisterType((*SendGroupMsgReq)(nil), "rpc.SendGroupMsgReq")
	proto.RegisterType((*SendGroupMsgRes)(nil), "rpc.SendGroupMsgRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LogicRPC service

type LogicRPCClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error)
	SendP2PMsg(ctx context.Context, in *SendP2PMsgReq, opts ...grpc.CallOption) (*SendP2PMsgRes, error)
	// client sync msg use current id
	SyncMsg(ctx context.Context, in *SyncMsgReq, opts ...grpc.CallOption) (*SyncMsgRes, error)
	AcceptP2PMsgAck(ctx context.Context, in *AcceptP2PMsgAckReq, opts ...grpc.CallOption) (*AcceptP2PMsgAckRes, error)
	SendGroupMsg(ctx context.Context, in *SendGroupMsgReq, opts ...grpc.CallOption) (*SendGroupMsgRes, error)
}

type logicRPCClient struct {
	cc *grpc.ClientConn
}

func NewLogicRPCClient(cc *grpc.ClientConn) LogicRPCClient {
	return &logicRPCClient{cc}
}

func (c *logicRPCClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := grpc.Invoke(ctx, "/rpc.LogicRPC/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicRPCClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error) {
	out := new(PingRes)
	err := grpc.Invoke(ctx, "/rpc.LogicRPC/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicRPCClient) SendP2PMsg(ctx context.Context, in *SendP2PMsgReq, opts ...grpc.CallOption) (*SendP2PMsgRes, error) {
	out := new(SendP2PMsgRes)
	err := grpc.Invoke(ctx, "/rpc.LogicRPC/SendP2PMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicRPCClient) SyncMsg(ctx context.Context, in *SyncMsgReq, opts ...grpc.CallOption) (*SyncMsgRes, error) {
	out := new(SyncMsgRes)
	err := grpc.Invoke(ctx, "/rpc.LogicRPC/SyncMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicRPCClient) AcceptP2PMsgAck(ctx context.Context, in *AcceptP2PMsgAckReq, opts ...grpc.CallOption) (*AcceptP2PMsgAckRes, error) {
	out := new(AcceptP2PMsgAckRes)
	err := grpc.Invoke(ctx, "/rpc.LogicRPC/AcceptP2PMsgAck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicRPCClient) SendGroupMsg(ctx context.Context, in *SendGroupMsgReq, opts ...grpc.CallOption) (*SendGroupMsgRes, error) {
	out := new(SendGroupMsgRes)
	err := grpc.Invoke(ctx, "/rpc.LogicRPC/SendGroupMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LogicRPC service

type LogicRPCServer interface {
	Login(context.Context, *LoginReq) (*LoginRes, error)
	Ping(context.Context, *PingReq) (*PingRes, error)
	SendP2PMsg(context.Context, *SendP2PMsgReq) (*SendP2PMsgRes, error)
	// client sync msg use current id
	SyncMsg(context.Context, *SyncMsgReq) (*SyncMsgRes, error)
	AcceptP2PMsgAck(context.Context, *AcceptP2PMsgAckReq) (*AcceptP2PMsgAckRes, error)
	SendGroupMsg(context.Context, *SendGroupMsgReq) (*SendGroupMsgRes, error)
}

func RegisterLogicRPCServer(s *grpc.Server, srv LogicRPCServer) {
	s.RegisterService(&_LogicRPC_serviceDesc, srv)
}

func _LogicRPC_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicRPCServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LogicRPC/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicRPCServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicRPC_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicRPCServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LogicRPC/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicRPCServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicRPC_SendP2PMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendP2PMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicRPCServer).SendP2PMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LogicRPC/SendP2PMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicRPCServer).SendP2PMsg(ctx, req.(*SendP2PMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicRPC_SyncMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicRPCServer).SyncMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LogicRPC/SyncMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicRPCServer).SyncMsg(ctx, req.(*SyncMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicRPC_AcceptP2PMsgAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptP2PMsgAckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicRPCServer).AcceptP2PMsgAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LogicRPC/AcceptP2PMsgAck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicRPCServer).AcceptP2PMsgAck(ctx, req.(*AcceptP2PMsgAckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicRPC_SendGroupMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicRPCServer).SendGroupMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LogicRPC/SendGroupMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicRPCServer).SendGroupMsg(ctx, req.(*SendGroupMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogicRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.LogicRPC",
	HandlerType: (*LogicRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LogicRPC_Login_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _LogicRPC_Ping_Handler,
		},
		{
			MethodName: "SendP2PMsg",
			Handler:    _LogicRPC_SendP2PMsg_Handler,
		},
		{
			MethodName: "SyncMsg",
			Handler:    _LogicRPC_SyncMsg_Handler,
		},
		{
			MethodName: "AcceptP2PMsgAck",
			Handler:    _LogicRPC_AcceptP2PMsgAck_Handler,
		},
		{
			MethodName: "SendGroupMsg",
			Handler:    _LogicRPC_SendGroupMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic.proto",
}

func init() { proto.RegisterFile("logic.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x6e, 0xb2, 0x49, 0xd7, 0x9c, 0x26, 0x44, 0x0f, 0x45, 0x97, 0xb5, 0x48, 0x18, 0x04, 0x03,
	0x62, 0x2e, 0x22, 0x78, 0x63, 0x6f, 0x42, 0xaa, 0x52, 0xb0, 0x10, 0x36, 0xea, 0x7d, 0x9c, 0x9d,
	0x0c, 0x21, 0xcd, 0xce, 0x76, 0x66, 0x72, 0xd1, 0x87, 0xf0, 0xb1, 0x7c, 0x2f, 0x99, 0xd9, 0xd9,
	0x9f, 0xfc, 0x08, 0x65, 0x21, 0x77, 0xfb, 0x7d, 0xdf, 0xd9, 0xf3, 0x3f, 0x07, 0x2e, 0xee, 0x05,
	0x5f, 0xd1, 0x51, 0x2a, 0x85, 0x16, 0xe8, 0xc9, 0x94, 0x92, 0x08, 0x9e, 0x7d, 0x17, 0x7c, 0x95,
	0x44, 0xec, 0x01, 0x9f, 0x83, 0xf7, 0xf3, 0xf6, 0x26, 0x68, 0x0c, 0x1a, 0x43, 0x2f, 0x32, 0x9f,
	0x78, 0x09, 0x6d, 0x2d, 0xd6, 0x2c, 0x09, 0x9a, 0x83, 0xc6, 0xb0, 0x13, 0x65, 0x00, 0xdf, 0x00,
	0x2c, 0x28, 0x65, 0x4a, 0x4d, 0xe2, 0x58, 0x06, 0x9e, 0x95, 0x2a, 0x0c, 0xb9, 0x2e, 0x7c, 0x2a,
	0x0c, 0xc0, 0x67, 0x52, 0x4e, 0x45, 0xcc, 0xac, 0xdf, 0x5e, 0x94, 0x43, 0x7c, 0x09, 0xe7, 0x4c,
	0xca, 0xb9, 0x96, 0xce, 0xb9, 0x43, 0xe4, 0x35, 0xf8, 0xb3, 0x55, 0xc2, 0x8f, 0x26, 0x44, 0x3e,
	0xe7, 0x62, 0x1d, 0xcf, 0x7f, 0x1a, 0xd0, 0x9b, 0xb3, 0x24, 0x9e, 0x8d, 0x67, 0x77, 0xca, 0x06,
	0xb8, 0x82, 0x8e, 0x12, 0x5b, 0x49, 0x59, 0x19, 0xa6, 0x24, 0x8c, 0xaa, 0x17, 0x92, 0x33, 0x6d,
	0xd4, 0x66, 0xa6, 0x16, 0x84, 0xe9, 0xcd, 0x46, 0xf1, 0xdb, 0x1b, 0xd7, 0x80, 0x0c, 0x98, 0xac,
	0x36, 0x8a, 0xff, 0x78, 0x4c, 0x59, 0xd0, 0xb2, 0x7c, 0x0e, 0x4d, 0x31, 0x1b, 0xc5, 0x83, 0xb6,
	0x65, 0xcd, 0x27, 0x99, 0xec, 0xa6, 0x53, 0xa7, 0xa4, 0x5f, 0x00, 0xf3, 0xc7, 0x84, 0xba, 0x72,
	0x0e, 0x07, 0x78, 0x05, 0x1d, 0xba, 0x95, 0x92, 0x25, 0xba, 0x2c, 0xa1, 0x20, 0x4c, 0x3c, 0x2d,
	0xf4, 0xe2, 0xde, 0x15, 0xe1, 0x45, 0x39, 0x24, 0x12, 0xba, 0x62, 0xb9, 0x54, 0x4c, 0x67, 0xc9,
	0x9d, 0xa0, 0x51, 0xae, 0x1d, 0xad, 0xb2, 0x1d, 0xeb, 0x4a, 0x2d, 0x35, 0x7a, 0x81, 0xef, 0xc1,
	0x4f, 0xc7, 0xe9, 0x9d, 0xe2, 0x2a, 0xf0, 0x06, 0xde, 0xf0, 0x62, 0xfc, 0x62, 0x24, 0x53, 0x3a,
	0xaa, 0xd6, 0x11, 0xe5, 0x16, 0x64, 0x09, 0x38, 0xa1, 0x94, 0xa5, 0x4e, 0x98, 0xd0, 0xf5, 0x49,
	0xf6, 0x81, 0x7c, 0x3d, 0x12, 0xa7, 0xce, 0xa0, 0x1f, 0xa0, 0x6f, 0x76, 0xe5, 0x9b, 0x14, 0xdb,
	0xf4, 0x49, 0xcb, 0x1b, 0x80, 0xcf, 0x8d, 0x71, 0x91, 0x6a, 0x0e, 0x9f, 0x3c, 0x8f, 0xe9, 0x7e,
	0xc8, 0x1a, 0x79, 0x8f, 0xff, 0x36, 0xb3, 0x63, 0x40, 0xa3, 0xd9, 0x14, 0xdf, 0x41, 0xdb, 0x1e,
	0x06, 0xec, 0xd9, 0xc9, 0xe4, 0x87, 0x27, 0xdc, 0x81, 0x8a, 0x9c, 0xe1, 0x5b, 0x68, 0x99, 0x67,
	0x8e, 0x5d, 0x2b, 0xb8, 0x73, 0x10, 0x56, 0x91, 0xb1, 0xfa, 0x04, 0x50, 0xbe, 0x1f, 0x44, 0xab,
	0xee, 0xbc, 0xef, 0xf0, 0x90, 0x33, 0xff, 0x7d, 0x00, 0xdf, 0x2d, 0x1a, 0xf6, 0x33, 0x83, 0xe2,
	0x09, 0x85, 0x7b, 0x84, 0x31, 0xff, 0x02, 0xfd, 0xbd, 0x11, 0xe2, 0x2b, 0x6b, 0x75, 0xb8, 0x40,
	0xe1, 0x7f, 0x04, 0xe3, 0xe6, 0x1a, 0xba, 0xd5, 0x76, 0xe2, 0x65, 0x91, 0x5b, 0x65, 0xa8, 0xe1,
	0x31, 0x56, 0x91, 0xb3, 0xdf, 0xe7, 0xf6, 0x66, 0x7f, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xae,
	0xa3, 0xc9, 0xe7, 0xc2, 0x05, 0x00, 0x00,
}
