// Code generated by protoc-gen-go.
// source: logic.proto
// DO NOT EDIT!

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LoginReq struct {
	UID   int64  `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type LoginRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *LoginRes) Reset()                    { *m = LoginRes{} }
func (m *LoginRes) String() string            { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()               {}
func (*LoginRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type PingReq struct {
	UID int64 `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
}

func (m *PingReq) Reset()                    { *m = PingReq{} }
func (m *PingReq) String() string            { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()               {}
func (*PingReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type PingRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *PingRes) Reset()                    { *m = PingRes{} }
func (m *PingRes) String() string            { return proto.CompactTextString(m) }
func (*PingRes) ProtoMessage()               {}
func (*PingRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

type SendP2PMsgReq struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	Msg       string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *SendP2PMsgReq) Reset()                    { *m = SendP2PMsgReq{} }
func (m *SendP2PMsgReq) String() string            { return proto.CompactTextString(m) }
func (*SendP2PMsgReq) ProtoMessage()               {}
func (*SendP2PMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

type SendP2PMsgRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *SendP2PMsgRes) Reset()                    { *m = SendP2PMsgRes{} }
func (m *SendP2PMsgRes) String() string            { return proto.CompactTextString(m) }
func (*SendP2PMsgRes) ProtoMessage()               {}
func (*SendP2PMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func init() {
	proto.RegisterType((*LoginReq)(nil), "rpc.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "rpc.LoginRes")
	proto.RegisterType((*PingReq)(nil), "rpc.PingReq")
	proto.RegisterType((*PingRes)(nil), "rpc.PingRes")
	proto.RegisterType((*SendP2PMsgReq)(nil), "rpc.SendP2PMsgReq")
	proto.RegisterType((*SendP2PMsgRes)(nil), "rpc.SendP2PMsgRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for LogicRPC service

type LogicRPCClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error)
	SendP2PMsg(ctx context.Context, in *SendP2PMsgReq, opts ...grpc.CallOption) (*SendP2PMsgRes, error)
}

type logicRPCClient struct {
	cc *grpc.ClientConn
}

func NewLogicRPCClient(cc *grpc.ClientConn) LogicRPCClient {
	return &logicRPCClient{cc}
}

func (c *logicRPCClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := grpc.Invoke(ctx, "/rpc.LogicRPC/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicRPCClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error) {
	out := new(PingRes)
	err := grpc.Invoke(ctx, "/rpc.LogicRPC/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicRPCClient) SendP2PMsg(ctx context.Context, in *SendP2PMsgReq, opts ...grpc.CallOption) (*SendP2PMsgRes, error) {
	out := new(SendP2PMsgRes)
	err := grpc.Invoke(ctx, "/rpc.LogicRPC/SendP2PMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LogicRPC service

type LogicRPCServer interface {
	Login(context.Context, *LoginReq) (*LoginRes, error)
	Ping(context.Context, *PingReq) (*PingRes, error)
	SendP2PMsg(context.Context, *SendP2PMsgReq) (*SendP2PMsgRes, error)
}

func RegisterLogicRPCServer(s *grpc.Server, srv LogicRPCServer) {
	s.RegisterService(&_LogicRPC_serviceDesc, srv)
}

func _LogicRPC_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicRPCServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LogicRPC/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicRPCServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicRPC_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicRPCServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LogicRPC/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicRPCServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicRPC_SendP2PMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendP2PMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicRPCServer).SendP2PMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LogicRPC/SendP2PMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicRPCServer).SendP2PMsg(ctx, req.(*SendP2PMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogicRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.LogicRPC",
	HandlerType: (*LogicRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LogicRPC_Login_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _LogicRPC_Ping_Handler,
		},
		{
			MethodName: "SendP2PMsg",
			Handler:    _LogicRPC_SendP2PMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor2,
}

func init() { proto.RegisterFile("logic.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0xc6, 0xb6, 0x76, 0x34, 0x20, 0x83, 0x48, 0x88, 0x1e, 0xca, 0x22, 0xd8, 0x53,
	0x0e, 0x11, 0xbc, 0xe8, 0x45, 0xea, 0x45, 0x50, 0x08, 0x5b, 0x3c, 0x7a, 0xd0, 0xed, 0xb2, 0x04,
	0x75, 0x37, 0xce, 0xae, 0x3f, 0xc4, 0x7f, 0x2c, 0xbb, 0x49, 0x1a, 0x83, 0x9e, 0x7a, 0x9b, 0x37,
	0x5f, 0x66, 0xe6, 0xf1, 0xb2, 0x70, 0xf0, 0x6e, 0x54, 0x25, 0xf2, 0x9a, 0x8c, 0x33, 0x18, 0x53,
	0x2d, 0x58, 0x01, 0xfb, 0x0f, 0x46, 0x55, 0x9a, 0xcb, 0x4f, 0x3c, 0x82, 0xf8, 0xe9, 0xfe, 0x2e,
	0x8d, 0x16, 0xd1, 0x32, 0xe6, 0xbe, 0xc4, 0x63, 0x98, 0x38, 0xf3, 0x26, 0x75, 0x3a, 0x5e, 0x44,
	0xcb, 0x39, 0x6f, 0x04, 0xbb, 0xd9, 0xce, 0x58, 0x4c, 0x61, 0x26, 0x89, 0x56, 0x66, 0x23, 0xc3,
	0x5c, 0xc2, 0x3b, 0x89, 0x27, 0x30, 0x95, 0x44, 0x6b, 0x47, 0xed, 0x70, 0xab, 0xd8, 0x29, 0xcc,
	0xca, 0x4a, 0xab, 0x7f, 0x0f, 0xb2, 0xeb, 0x0e, 0xee, 0xb2, 0xf9, 0x19, 0x92, 0xb5, 0xd4, 0x9b,
	0xb2, 0x28, 0x1f, 0x6d, 0xd8, 0x7f, 0x06, 0x73, 0x6b, 0xbe, 0x48, 0xc8, 0xfe, 0x4a, 0xdf, 0xf0,
	0xd4, 0xbd, 0x90, 0x92, 0xce, 0xd3, 0x71, 0x43, 0xb7, 0x0d, 0xef, 0xed, 0xc3, 0xaa, 0x34, 0x0e,
	0x17, 0x7c, 0xc9, 0x6e, 0x87, 0xeb, 0x77, 0x70, 0x58, 0x7c, 0x47, 0x4d, 0x74, 0x82, 0x97, 0x2b,
	0xbc, 0x80, 0x49, 0x88, 0x11, 0x93, 0x9c, 0x6a, 0x91, 0x77, 0xbf, 0x21, 0x1b, 0x48, 0xcb, 0x46,
	0x78, 0x0e, 0x7b, 0x3e, 0x14, 0x3c, 0x0c, 0xa0, 0x0d, 0x2f, 0xfb, 0xad, 0xfc, 0x57, 0x57, 0x00,
	0xbd, 0x3d, 0xc4, 0x40, 0x07, 0x71, 0x64, 0x7f, 0x7b, 0x96, 0x8d, 0x5e, 0xa7, 0xe1, 0x35, 0x5c,
	0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xaa, 0x84, 0x8d, 0x1c, 0x02, 0x00, 0x00,
}
