// Code generated by protoc-gen-go.
// source: manager.proto
// DO NOT EDIT!

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MGExceptionMsgReq struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	Msg       string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *MGExceptionMsgReq) Reset()                    { *m = MGExceptionMsgReq{} }
func (m *MGExceptionMsgReq) String() string            { return proto.CompactTextString(m) }
func (*MGExceptionMsgReq) ProtoMessage()               {}
func (*MGExceptionMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *MGExceptionMsgReq) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *MGExceptionMsgReq) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *MGExceptionMsgReq) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *MGExceptionMsgReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type MGExceptionMsgRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *MGExceptionMsgRes) Reset()                    { *m = MGExceptionMsgRes{} }
func (m *MGExceptionMsgRes) String() string            { return proto.CompactTextString(m) }
func (*MGExceptionMsgRes) ProtoMessage()               {}
func (*MGExceptionMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *MGExceptionMsgRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *MGExceptionMsgRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

type MGOfflineMsgReq struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *MGOfflineMsgReq) Reset()                    { *m = MGOfflineMsgReq{} }
func (m *MGOfflineMsgReq) String() string            { return proto.CompactTextString(m) }
func (*MGOfflineMsgReq) ProtoMessage()               {}
func (*MGOfflineMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *MGOfflineMsgReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type OfflineMsg struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	Msg       string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *OfflineMsg) Reset()                    { *m = OfflineMsg{} }
func (m *OfflineMsg) String() string            { return proto.CompactTextString(m) }
func (*OfflineMsg) ProtoMessage()               {}
func (*OfflineMsg) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *OfflineMsg) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *OfflineMsg) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *OfflineMsg) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *OfflineMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type MGOfflineMsgRes struct {
	ErrCode uint32        `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string        `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
	Msgs    []*OfflineMsg `protobuf:"bytes,3,rep,name=msgs" json:"msgs,omitempty"`
}

func (m *MGOfflineMsgRes) Reset()                    { *m = MGOfflineMsgRes{} }
func (m *MGOfflineMsgRes) String() string            { return proto.CompactTextString(m) }
func (*MGOfflineMsgRes) ProtoMessage()               {}
func (*MGOfflineMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *MGOfflineMsgRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *MGOfflineMsgRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

func (m *MGOfflineMsgRes) GetMsgs() []*OfflineMsg {
	if m != nil {
		return m.Msgs
	}
	return nil
}

// Sync
type MGSyncMsgReq struct {
	UID       int64 `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
	CurrentID int64 `protobuf:"varint,2,opt,name=currentID" json:"currentID,omitempty"`
	TotalID   int64 `protobuf:"varint,3,opt,name=totalID" json:"totalID,omitempty"`
}

func (m *MGSyncMsgReq) Reset()                    { *m = MGSyncMsgReq{} }
func (m *MGSyncMsgReq) String() string            { return proto.CompactTextString(m) }
func (*MGSyncMsgReq) ProtoMessage()               {}
func (*MGSyncMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *MGSyncMsgReq) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *MGSyncMsgReq) GetCurrentID() int64 {
	if m != nil {
		return m.CurrentID
	}
	return 0
}

func (m *MGSyncMsgReq) GetTotalID() int64 {
	if m != nil {
		return m.TotalID
	}
	return 0
}

type MGSyncMsgRes struct {
	ErrCode uint32                   `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string                   `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
	Msgs    []*MGSyncMsgResOffsetMsg `protobuf:"bytes,3,rep,name=Msgs" json:"Msgs,omitempty"`
}

func (m *MGSyncMsgRes) Reset()                    { *m = MGSyncMsgRes{} }
func (m *MGSyncMsgRes) String() string            { return proto.CompactTextString(m) }
func (*MGSyncMsgRes) ProtoMessage()               {}
func (*MGSyncMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *MGSyncMsgRes) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *MGSyncMsgRes) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

func (m *MGSyncMsgRes) GetMsgs() []*MGSyncMsgResOffsetMsg {
	if m != nil {
		return m.Msgs
	}
	return nil
}

type MGSyncMsgResOffsetMsg struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	GroupID   int64  `protobuf:"varint,3,opt,name=groupID" json:"groupID,omitempty"`
	MsgType   string `protobuf:"bytes,4,opt,name=msgType" json:"msgType,omitempty"`
	MsgID     string `protobuf:"bytes,5,opt,name=msgID" json:"msgID,omitempty"`
	Msg       string `protobuf:"bytes,6,opt,name=msg" json:"msg,omitempty"`
}

func (m *MGSyncMsgResOffsetMsg) Reset()                    { *m = MGSyncMsgResOffsetMsg{} }
func (m *MGSyncMsgResOffsetMsg) String() string            { return proto.CompactTextString(m) }
func (*MGSyncMsgResOffsetMsg) ProtoMessage()               {}
func (*MGSyncMsgResOffsetMsg) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6, 0} }

func (m *MGSyncMsgResOffsetMsg) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *MGSyncMsgResOffsetMsg) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *MGSyncMsgResOffsetMsg) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *MGSyncMsgResOffsetMsg) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MGSyncMsgResOffsetMsg) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *MGSyncMsgResOffsetMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*MGExceptionMsgReq)(nil), "rpc.MGExceptionMsgReq")
	proto.RegisterType((*MGExceptionMsgRes)(nil), "rpc.MGExceptionMsgRes")
	proto.RegisterType((*MGOfflineMsgReq)(nil), "rpc.MGOfflineMsgReq")
	proto.RegisterType((*OfflineMsg)(nil), "rpc.offlineMsg")
	proto.RegisterType((*MGOfflineMsgRes)(nil), "rpc.MGOfflineMsgRes")
	proto.RegisterType((*MGSyncMsgReq)(nil), "rpc.MGSyncMsgReq")
	proto.RegisterType((*MGSyncMsgRes)(nil), "rpc.MGSyncMsgRes")
	proto.RegisterType((*MGSyncMsgResOffsetMsg)(nil), "rpc.MGSyncMsgRes.offsetMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ManagerServerRPC service

type ManagerServerRPCClient interface {
	SetExceptionMsg(ctx context.Context, in *MGExceptionMsgReq, opts ...grpc.CallOption) (*MGExceptionMsgRes, error)
	GetOfflineMsgs(ctx context.Context, in *MGOfflineMsgReq, opts ...grpc.CallOption) (*MGOfflineMsgRes, error)
	Sync(ctx context.Context, in *MGSyncMsgReq, opts ...grpc.CallOption) (*MGSyncMsgRes, error)
}

type managerServerRPCClient struct {
	cc *grpc.ClientConn
}

func NewManagerServerRPCClient(cc *grpc.ClientConn) ManagerServerRPCClient {
	return &managerServerRPCClient{cc}
}

func (c *managerServerRPCClient) SetExceptionMsg(ctx context.Context, in *MGExceptionMsgReq, opts ...grpc.CallOption) (*MGExceptionMsgRes, error) {
	out := new(MGExceptionMsgRes)
	err := grpc.Invoke(ctx, "/rpc.ManagerServerRPC/SetExceptionMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServerRPCClient) GetOfflineMsgs(ctx context.Context, in *MGOfflineMsgReq, opts ...grpc.CallOption) (*MGOfflineMsgRes, error) {
	out := new(MGOfflineMsgRes)
	err := grpc.Invoke(ctx, "/rpc.ManagerServerRPC/GetOfflineMsgs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServerRPCClient) Sync(ctx context.Context, in *MGSyncMsgReq, opts ...grpc.CallOption) (*MGSyncMsgRes, error) {
	out := new(MGSyncMsgRes)
	err := grpc.Invoke(ctx, "/rpc.ManagerServerRPC/Sync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ManagerServerRPC service

type ManagerServerRPCServer interface {
	SetExceptionMsg(context.Context, *MGExceptionMsgReq) (*MGExceptionMsgRes, error)
	GetOfflineMsgs(context.Context, *MGOfflineMsgReq) (*MGOfflineMsgRes, error)
	Sync(context.Context, *MGSyncMsgReq) (*MGSyncMsgRes, error)
}

func RegisterManagerServerRPCServer(s *grpc.Server, srv ManagerServerRPCServer) {
	s.RegisterService(&_ManagerServerRPC_serviceDesc, srv)
}

func _ManagerServerRPC_SetExceptionMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MGExceptionMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServerRPCServer).SetExceptionMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ManagerServerRPC/SetExceptionMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServerRPCServer).SetExceptionMsg(ctx, req.(*MGExceptionMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerServerRPC_GetOfflineMsgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MGOfflineMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServerRPCServer).GetOfflineMsgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ManagerServerRPC/GetOfflineMsgs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServerRPCServer).GetOfflineMsgs(ctx, req.(*MGOfflineMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerServerRPC_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MGSyncMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServerRPCServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ManagerServerRPC/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServerRPCServer).Sync(ctx, req.(*MGSyncMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagerServerRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.ManagerServerRPC",
	HandlerType: (*ManagerServerRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetExceptionMsg",
			Handler:    _ManagerServerRPC_SetExceptionMsg_Handler,
		},
		{
			MethodName: "GetOfflineMsgs",
			Handler:    _ManagerServerRPC_GetOfflineMsgs_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _ManagerServerRPC_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager.proto",
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0x9b, 0x7a, 0xbb, 0xd5, 0x0e, 0x94, 0xdd, 0x5a, 0x55, 0x15, 0x05, 0x0e, 0x2b, 0xf7,
	0xb2, 0xa7, 0x20, 0x95, 0x3b, 0x97, 0x6d, 0x15, 0xf5, 0x10, 0x81, 0x1c, 0x90, 0xb8, 0x86, 0x74,
	0x6a, 0x56, 0x6a, 0xe2, 0x74, 0xec, 0x00, 0x7d, 0x12, 0x1e, 0x80, 0x87, 0xe1, 0xb5, 0x90, 0xb3,
	0xde, 0xb8, 0xdd, 0xee, 0xa9, 0x48, 0xdc, 0xfc, 0xff, 0xe3, 0x78, 0xe6, 0xf3, 0x8c, 0x03, 0x47,
	0x75, 0xd9, 0x94, 0x0a, 0x29, 0x6d, 0x49, 0x5b, 0xcd, 0x19, 0xb5, 0x95, 0xf8, 0x01, 0xc7, 0x79,
	0x76, 0xf9, 0xb3, 0xc2, 0xd6, 0xae, 0x74, 0x93, 0x1b, 0x25, 0xf1, 0x8e, 0xbf, 0x81, 0x89, 0xd1,
	0x1d, 0x55, 0xf8, 0xf9, 0xea, 0x22, 0x8e, 0xe6, 0xd1, 0x82, 0xc9, 0x60, 0xb8, 0xa8, 0x2d, 0x49,
	0xa1, 0x75, 0xd1, 0xfd, 0x75, 0x74, 0x30, 0xf8, 0x09, 0x1c, 0xd4, 0x46, 0x5d, 0x5d, 0xc4, 0x6c,
	0x1e, 0x2d, 0x26, 0x72, 0x2d, 0xf8, 0x0c, 0x58, 0x6d, 0x54, 0x3c, 0xea, 0x3d, 0xb7, 0x14, 0x97,
	0x4f, 0x13, 0x1b, 0x1e, 0xc3, 0x21, 0x12, 0x2d, 0xf5, 0x35, 0xf6, 0x69, 0x8f, 0xe4, 0x46, 0xf2,
	0x53, 0x18, 0x23, 0x51, 0x61, 0xa9, 0xcf, 0x38, 0x91, 0x5e, 0x89, 0x33, 0x98, 0xe6, 0xd9, 0x87,
	0x9b, 0x9b, 0xdb, 0x55, 0x83, 0xbe, 0xfa, 0x19, 0xb0, 0x6e, 0x75, 0xed, 0xeb, 0x76, 0x4b, 0xd1,
	0x02, 0xe8, 0x61, 0xcb, 0x7f, 0xa1, 0xfb, 0xb6, 0x5d, 0xd6, 0x33, 0xd8, 0xf8, 0x19, 0x8c, 0x6a,
	0xa3, 0x4c, 0xcc, 0xe6, 0x6c, 0xf1, 0xe2, 0x7c, 0x9a, 0x52, 0x5b, 0xa5, 0x81, 0x43, 0xf6, 0x41,
	0xf1, 0x05, 0x5e, 0xe6, 0x59, 0x71, 0xdf, 0x54, 0x81, 0x3e, 0x70, 0x31, 0x4f, 0x54, 0x75, 0x44,
	0xd8, 0xd8, 0x40, 0x34, 0x18, 0xae, 0x2c, 0xab, 0x6d, 0x79, 0xeb, 0x99, 0x98, 0xdc, 0x48, 0xf1,
	0x6b, 0xff, 0xd1, 0xd1, 0xcf, 0x21, 0x78, 0x0b, 0xa3, 0x3c, 0x10, 0xbc, 0xee, 0x09, 0x1e, 0x1e,
	0xe9, 0x70, 0x0c, 0xda, 0x9e, 0xc6, 0x6d, 0x4c, 0x7e, 0x47, 0x30, 0x19, 0xbc, 0x7f, 0xea, 0x54,
	0x0c, 0x87, 0x8a, 0x74, 0xd7, 0x06, 0x2e, 0x2f, 0x5d, 0xa4, 0x36, 0xea, 0xd3, 0x7d, 0x8b, 0xbe,
	0x63, 0x1b, 0x19, 0xba, 0x7b, 0xb0, 0xa3, 0xbb, 0xe3, 0xa1, 0xbb, 0xe7, 0x7f, 0x22, 0x98, 0xe5,
	0xeb, 0xb7, 0x54, 0x20, 0x7d, 0x47, 0x92, 0x1f, 0x97, 0x7c, 0x09, 0xd3, 0x02, 0xed, 0xc3, 0x89,
	0xe6, 0xa7, 0x1e, 0x78, 0xeb, 0x7d, 0x25, 0xbb, 0x7d, 0x23, 0xf6, 0xf8, 0x7b, 0x78, 0x95, 0xa1,
	0x0d, 0x83, 0x63, 0xf8, 0x89, 0xdf, 0xfb, 0x68, 0xc6, 0x93, 0x5d, 0xae, 0xfb, 0x3e, 0x85, 0x91,
	0xbb, 0x5d, 0x7e, 0xbc, 0x7d, 0xd5, 0x77, 0xc9, 0x13, 0xcb, 0x88, 0xbd, 0xaf, 0xe3, 0xfe, 0x57,
	0xf0, 0xee, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xf0, 0xbc, 0x04, 0x1b, 0x04, 0x00, 0x00,
}
