// Code generated by protoc-gen-go.
// source: msg_server.proto
// DO NOT EDIT!

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LoginReq struct {
	UID   int64  `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type LoginRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *LoginRes) Reset()                    { *m = LoginRes{} }
func (m *LoginRes) String() string            { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()               {}
func (*LoginRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type SendP2PMsgReq struct {
	UID       int64  `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	Msg       string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *SendP2PMsgReq) Reset()                    { *m = SendP2PMsgReq{} }
func (m *SendP2PMsgReq) String() string            { return proto.CompactTextString(m) }
func (*SendP2PMsgReq) ProtoMessage()               {}
func (*SendP2PMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type SendP2PMsgRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr" json:"errStr,omitempty"`
}

func (m *SendP2PMsgRes) Reset()                    { *m = SendP2PMsgRes{} }
func (m *SendP2PMsgRes) String() string            { return proto.CompactTextString(m) }
func (*SendP2PMsgRes) ProtoMessage()               {}
func (*SendP2PMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func init() {
	proto.RegisterType((*LoginReq)(nil), "rpc.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "rpc.LoginRes")
	proto.RegisterType((*SendP2PMsgReq)(nil), "rpc.SendP2PMsgReq")
	proto.RegisterType((*SendP2PMsgRes)(nil), "rpc.SendP2PMsgRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for MsgServerRPC service

type MsgServerRPCClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
	SendP2PMsg(ctx context.Context, in *SendP2PMsgReq, opts ...grpc.CallOption) (*SendP2PMsgRes, error)
}

type msgServerRPCClient struct {
	cc *grpc.ClientConn
}

func NewMsgServerRPCClient(cc *grpc.ClientConn) MsgServerRPCClient {
	return &msgServerRPCClient{cc}
}

func (c *msgServerRPCClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := grpc.Invoke(ctx, "/rpc.MsgServerRPC/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServerRPCClient) SendP2PMsg(ctx context.Context, in *SendP2PMsgReq, opts ...grpc.CallOption) (*SendP2PMsgRes, error) {
	out := new(SendP2PMsgRes)
	err := grpc.Invoke(ctx, "/rpc.MsgServerRPC/SendP2PMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MsgServerRPC service

type MsgServerRPCServer interface {
	Login(context.Context, *LoginReq) (*LoginRes, error)
	SendP2PMsg(context.Context, *SendP2PMsgReq) (*SendP2PMsgRes, error)
}

func RegisterMsgServerRPCServer(s *grpc.Server, srv MsgServerRPCServer) {
	s.RegisterService(&_MsgServerRPC_serviceDesc, srv)
}

func _MsgServerRPC_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServerRPCServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MsgServerRPC/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServerRPCServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgServerRPC_SendP2PMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendP2PMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServerRPCServer).SendP2PMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MsgServerRPC/SendP2PMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServerRPCServer).SendP2PMsg(ctx, req.(*SendP2PMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgServerRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.MsgServerRPC",
	HandlerType: (*MsgServerRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MsgServerRPC_Login_Handler,
		},
		{
			MethodName: "SendP2PMsg",
			Handler:    _MsgServerRPC_SendP2PMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("msg_server.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xbb, 0x0d, 0xad, 0x76, 0x70, 0xa1, 0x0c, 0x22, 0xa1, 0x78, 0x28, 0xb9, 0xd8, 0xd3,
	0x1e, 0x56, 0xf0, 0xe4, 0x45, 0xea, 0x45, 0xb0, 0xb0, 0x66, 0xf1, 0x2c, 0xda, 0x0e, 0x41, 0xa4,
	0x9b, 0x75, 0x26, 0xf8, 0xfb, 0x25, 0xb1, 0xeb, 0xb2, 0xe8, 0xa9, 0xb7, 0x79, 0x5f, 0xf2, 0x66,
	0x32, 0x2f, 0x30, 0xdf, 0x8b, 0x7b, 0x11, 0xe2, 0x2f, 0xe2, 0xa2, 0x65, 0x1f, 0x3c, 0x2a, 0x6e,
	0xb7, 0xa6, 0x84, 0xd3, 0x47, 0xef, 0xde, 0x1b, 0x4b, 0x9f, 0x38, 0x07, 0xf5, 0xfc, 0x70, 0xaf,
	0xb3, 0x65, 0xb6, 0x52, 0x36, 0x96, 0x78, 0x0e, 0x93, 0xe0, 0x3f, 0xa8, 0xd1, 0xe3, 0x65, 0xb6,
	0x9a, 0xd9, 0x1f, 0x61, 0x6e, 0x7f, 0x3d, 0x82, 0x1a, 0x4e, 0x88, 0x79, 0xed, 0x77, 0x94, 0x7c,
	0xb9, 0xed, 0x24, 0x5e, 0xc0, 0x94, 0x98, 0xeb, 0xc0, 0x07, 0xf3, 0x41, 0x99, 0x27, 0xc8, 0x6b,
	0x6a, 0x76, 0x55, 0x59, 0x6d, 0xc4, 0xfd, 0x3f, 0xf6, 0x12, 0x66, 0xe1, 0x95, 0x1d, 0x85, 0xc8,
	0xc7, 0x89, 0xf7, 0x20, 0xde, 0xdf, 0x8b, 0xd3, 0x2a, 0x75, 0x8d, 0xa5, 0xb9, 0x1b, 0xb6, 0x3c,
	0xe2, 0x55, 0xa5, 0x87, 0xb3, 0x8d, 0xb8, 0x3a, 0xe5, 0x63, 0xab, 0x35, 0x5e, 0xc1, 0x24, 0xed,
	0x88, 0x79, 0xc1, 0xed, 0xb6, 0xe8, 0x32, 0x5a, 0x0c, 0xa4, 0x98, 0x11, 0xde, 0x00, 0xf4, 0xb3,
	0x11, 0xd3, 0xf1, 0x60, 0xbf, 0xc5, 0x5f, 0x26, 0x66, 0xf4, 0x36, 0x4d, 0x9f, 0x70, 0xfd, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xb3, 0x1f, 0xf9, 0xe7, 0x98, 0x01, 0x00, 0x00,
}
